Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -46,20 +46,18 @@ jobs:
           git lfs pull
           
       - name: Extract Archive
-        run: tar -xvf .venv.tar.gz
-          
+        run: |
+          echo "\n\n[$(date '+%Y-%m-%d %H:%M:%S')] [>>>>>>>>>>] Starting the test mode [>>>>>>>>>>]\n" >> ~/status.txt
+          # Verify file existence and size
+          ls -lh .venv.tar.gz || echo "File not found"
+          echo "\n[$(date '+%Y-%m-%d %H:%M:%S')] Extracting environment...\n" >> ~/status.txt
+          tar -xzf .venv.tar.gz || { echo "Tar failed"; exit 1; }
+                    
       - name: Run Application
         run: |
-          echo "[$(date '+%Y-%m-%d %H:%M:%S')] Starting the test mode [>>>>>>>>>>]" >> ~/status.txt
-          # Verify file existence and size
-          # ls -lh .venv.tar.gz || echo "File not found"
-
-          # echo "[$(date '+%Y-%m-%d %H:%M:%S')] Extracting environment..." >> ~/status.txt
-          # tar -xzf .venv.tar.gz || { echo "Tar failed"; exit 1; }
-
           source .venv/bin/activate
           python test_mode.py | tee -a ~/status.txt
-          echo "[$(date '+%Y-%m-%d %H:%M:%S')] Execution completed! [<<<<<<<<<<]" >> ~/status.txt
+          echo "\n[$(date '+%Y-%m-%d %H:%M:%S')] [<<<<<<<<<<] Execution completed! [<<<<<<<<<<]\n" >> ~/status.txt
 
   deploy:
     runs-on: self-hosted
